name: 'BedrockConnect'
description: 'Join any Minecraft Bedrock Edition server IP on Xbox One, Nintendo Switch, and PS4/PS5'
version: '1.43.0'
slug: 'bedrock_connect'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  19132/udp: 19132
ports_description:
  19132/udp: 'Port of the server (Should only be changed for debugging on PC. Port needs to be on 19132 for the bypass to work on game consoles)'
